[package]
name = "twitch-hls-client-uri-protocol"
version = "0.1.5"
edition = "2024"
license = "AGPL-3.0-only"

[dependencies]
percent-encoding = "2.3.2"
uriparse = "0.6.4"

[profile.release]
lto = true
codegen-units = 1
strip = true
